name: SAMap
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pip
  - pybind11
  - h5py=3.8.0
  - leidenalg
  - python-igraph
  - texttable

# Install SAMap dependencies availabe in conda
# conda create -n SAMap -c conda-forge python=3.9 numpy=1.23.5 pip pybind11 h5py=3.8.0 leidenalg python-igraph texttable
# conda activate SAMap